// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloGrpc.proto

package com.demo.grpc.service.grpc;

public interface HelloGrpcReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloGrpcReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *接口返回内容
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <pre>
   *接口返回内容
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
