// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloGrpc.proto

package com.demo.grpc.service.grpc;

public interface HelloGrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloGrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *输入的字符串内容
   * </pre>
   *
   * <code>string inputString = 1;</code>
   */
  java.lang.String getInputString();
  /**
   * <pre>
   *输入的字符串内容
   * </pre>
   *
   * <code>string inputString = 1;</code>
   */
  com.google.protobuf.ByteString
      getInputStringBytes();
}
